### ISSUE TITLE
Server Error: Request could not be identified as panel or client

### ISSUE THREAD

**Issue by Metaspl01t-006** [TR-SLimey/wraith#1]
Single instance check passed, starting
/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py:842: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn((

[CLIENT]:
{"message_type": "heartbeat", "data": {"info": {"running_as_user": "kali", "available_ram": 1023672320, "used_ram": 568958976, "available_disk": 67508670464, "used_disk": 11234516992, "local_ip": "10.0.2.15"}, "wraith_id": null}}

[SERVER]:
{"status": "ERROR", "requester_type": "unknown", "message": "Request could not be identified as panel or client"}
ISCRYPT: False

[CLIENT]:
{"message_type": "login", "data": {"osname": "kali", "ostype": "Linux-5.9.0-kali2-amd64-x86_64-with-glibc2.29", "macaddr": 8796758542364, "wraith_version": "3.0.0", "wraith_start_time": 1606128609.6322184, "this_child_start_time": 1606128609.632221}}

[SERVER]:
{"status": "ERROR", "requester_type": "unknown", "message": "Request could not be identified as panel or client"}
ISCRYPT: False

Failed to log in, waiting 10 seconds before re-try
^CTraceback (most recent call last):
  File "wraith.py", line 283, in <module>
    time.sleep(10)
KeyboardInterrupt

**Comment by Metaspl01t-006** [comment]
Different default keys for server and client

**Comment by TR-SLimey** [comment]
> Different default keys for server and client

That's intentional, as the keys should always be changed - this more or less ensures that. Do note though, that the project is in development and most/all features are very unlikely to work.

**Comment by TR-SLimey** [comment]
Is this issue purely about the fact that the default keys are different or does the error persist when when the keys are the same?

**Comment by Spl01ter** [comment]
Clients get disconnected periodically. Can fix that by changing the heartbeat time.

**Comment by Spl01ter** [comment]
But everything else is fine

**Comment by Spl01ter** [comment]
Kinda

**Comment by TR-SLimey** [comment]
Yeah, disconnects do happen. I remember that being a big flaw. As you said, adjusting the heartbeat time or the kick delay is a temporary fix until v4 is released - unfortunately I have nothing better to offer as a solution :(
