### ISSUE TITLE
Login  success but displays failure message

### ISSUE THREAD

**Issue by Spl01ter** [TR-SLimey/wraith#2]
[CLIENT]:
{"message_type": "login", "data": {"osname": "kali", "ostype": "Linux-5.9.0-kali2-amd64-x86_64-with-glibc2.29", "macaddr": 8796758542364, "wraith_version": "3.0.0", "wraith_start_time": 1606128940.8567538, "this_child_start_time": 1606128940.8567555}}

[SERVER]:
{"requester_type": "wraith", "switch_key": "256c416978c99e254270cc8bd036526b", "server_id": "SomeFingerprint_", "status": "SUCCESS", "message": "Successfully logged in", "wraith_id": "f6642177-5ee8-4123-804d-eb9d54cfe734"}
ISCRYPT: True

Failed to log in, waiting 10 seconds before re-try
/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py:842: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn((

[CLIENT]:
{"message_type": "login", "data": {"osname": "kali", "ostype": "Linux-5.9.0-kali2-amd64-x86_64-with-glibc2.29", "macaddr": 8796758542364, "wraith_version": "3.0.0", "wraith_start_time": 1606128940.8567538, "this_child_start_time": 1606128940.8567555}}

**Comment by TR-SLimey** [comment]
So it would seem. Technically I don't work on v3.0.0 anymore but I'll look into it. Thanks for reporting.

**Comment by TR-SLimey** [comment]
Could not reproduce. Every reply where the server replied positively resulted in a successful login. Maybe you forgot to edit the server fingerprint to match on both Wraith and the API?

**Comment by Spl01ter** [comment]
I did

**Comment by Spl01ter** [comment]
But the client disconnected and reconnected too often.

**Comment by Spl01ter** [comment]
So the 'ALL' variable might not be storing the right id
